homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:General:index }

pedir_cita:
    pattern:  /pedir-cita
    defaults: { _controller: FrontendBundle:General:pedirCita }
    requirements:
        _method:  GET

pedir_cita_submit:
    pattern:  /pedir-cita
    defaults: { _controller: FrontendBundle:General:pedirCita }
    requirements:
        _method:  POST

contacto:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:General:contacto }
    requirements:
        _method:  GET

contacto_submit:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:General:contacto }
    requirements:
        _method:  POST

licencia:
    resource: "@FrontendBundle/Resources/config/routing_licencia.yml"
    prefix:   /licencias-permisos/

avisador:
    resource: "@FrontendBundle/Resources/config/routing_avisador.yml"
    prefix:   /avisador-caducidad/

terminos_condiciones:
    pattern:  /terminos-condiciones-uso
    defaults: { _controller: FrontendBundle:General:terminosCondiciones }

sitemap:
    pattern:  /sitemap
    defaults: { _controller: FrontendBundle:General:sitemap }
